### ISSUE TITLE
Run code

### ISSUE THREAD

**Issue by LWC13** [wangzb11/AGRAN#2]
Hi, it's a great work and thank for your source code. However, when I try to run your code(main.py) and see the metrics, I found that the result is quite different from the paper. (I follow the parameters setting of Foursquare, four-sin dataset in your code) Thus, I would like to ask is there any parameters should I chang or is there any file I should run before I run main.py? Thanks for your response!

—————————————————————-
After I change another device to run the code, the problem is solved ! The reason why previous results are quite different may cause by the version! Sorry for bother you ><

**Comment by LWC13** [comment]
Hi, after I change another device to run the code, the metrics are similar to yours! Previous results may cause by the version of PyTorch or GPU, sorry for bother you!

**Comment by Nina1234y** [comment]
Hi @LWC13, I am experiencing the same issue. Would you mind sharing what device you used that helped solve this problem?

**Comment by LWC13** [comment]
Hello @Nina1234y , below are the specifics of the Python environment, library versions, and the hardware I utilized to execute the code:

Python version: 3.8.16
PyTorch version: 1.8.1
SciPy version: 1.10.1
NumPy version: 1.23.5
Hardware: NVIDIA GeForce RTX 2080
I hope this information assists you!

P.S. The outputs in the picture are generated from running the code with these specific versions and on the mentioned device.
<img width="1033" alt="截圖 2024-03-31 凌晨12 41 21" src="https://github.com/wangzb11/AGRAN/assets/121170101/94154e90-3297-4fd2-85ae-7f2e93d2e3fd">

**Comment by Nina1234y** [comment]
@LWC13 Thank you, that works!
